# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: native_imaging
version: 0.0.1
description: Dart bindings for Imaging from Pillow with jpeg and blurhash encoders
homepage: https://famedly.gitlab.io/libraries/native_imaging/
repository: https://gitlab.com/famedly/libraries/native_imaging

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  js: ^0.6.0
  ffi: ^1.0.0
  test: ^1.9.0
  pedantic: ^1.9.2

dev_dependencies:
  test_coverage: ^0.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_imaging
        pluginClass: NativeImagingPlugin
      ios:
        pluginClass: NativeImagingPlugin
